package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.AlarmConfigRecord;
import org.apache.ibatis.jdbc.SQL;

public class AlarmConfigRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_config
     *
     * @mbg.generated
     */
    public String insertSelective(AlarmConfigRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("alarm_config");
        
        if (record.getDevId() != null) {
            sql.VALUES("dev_id", "#{devId,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmTypeId() != null) {
            sql.VALUES("alarm_type_id", "#{alarmTypeId,jdbcType=INTEGER}");
        }
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getForewarnUplimit() != null) {
            sql.VALUES("forewarn_uplimit", "#{forewarnUplimit,jdbcType=INTEGER}");
        }
        
        if (record.getForewarnLowlimit() != null) {
            sql.VALUES("forewarn_lowlimit", "#{forewarnLowlimit,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmwarnUplimit() != null) {
            sql.VALUES("alarmwarn_uplimit", "#{alarmwarnUplimit,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmwarnLowlimit() != null) {
            sql.VALUES("alarmwarn_lowlimit", "#{alarmwarnLowlimit,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_config
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(AlarmConfigRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("alarm_config");
        
        if (record.getId() != null) {
            sql.SET("id = #{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getForewarnUplimit() != null) {
            sql.SET("forewarn_uplimit = #{forewarnUplimit,jdbcType=INTEGER}");
        }
        
        if (record.getForewarnLowlimit() != null) {
            sql.SET("forewarn_lowlimit = #{forewarnLowlimit,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmwarnUplimit() != null) {
            sql.SET("alarmwarn_uplimit = #{alarmwarnUplimit,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmwarnLowlimit() != null) {
            sql.SET("alarmwarn_lowlimit = #{alarmwarnLowlimit,jdbcType=INTEGER}");
        }
        
        sql.WHERE("dev_id = #{devId,jdbcType=INTEGER}");
        sql.WHERE("alarm_type_id = #{alarmTypeId,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}