package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.CameraDO;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface CameraDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera
     *
     * @mbg.generated
     */
    @Delete({
            "delete from camera",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera
     *
     * @mbg.generated
     */
    @Insert({
            "insert into camera (id, name, ",
            "sn, code, url_hls, ",
            "url_hls_hd, rtmp, ",
            "rtmp_hd, ws_addr, ",
            "ias_id, farmland_id, ",
            "area_id, location, ",
            "capability)",
            "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
            "#{sn,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, #{urlHls,jdbcType=VARCHAR}, ",
            "#{urlHlsHd,jdbcType=VARCHAR}, #{rtmp,jdbcType=VARCHAR}, ",
            "#{rtmpHd,jdbcType=VARCHAR}, #{wsAddr,jdbcType=VARCHAR}, ",
            "#{iasId,jdbcType=INTEGER}, #{farmlandId,jdbcType=INTEGER}, ",
            "#{areaId,jdbcType=INTEGER}, #{location,jdbcType=INTEGER}, ",
            "#{capability,jdbcType=OTHER})"
    })
    int insert(CameraDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera
     *
     * @mbg.generated
     */
    @InsertProvider(type = CameraDOSqlProvider.class, method = "insertSelective")
    int insertSelective(CameraDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, name, sn, code, url_hls, url_hls_hd, rtmp, rtmp_hd, ws_addr, ias_id, farmland_id, ",
            "area_id, location, capability",
            "from camera",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
            @Result(column = "sn", property = "sn", jdbcType = JdbcType.VARCHAR),
            @Result(column = "code", property = "code", jdbcType = JdbcType.VARCHAR),
            @Result(column = "url_hls", property = "urlHls", jdbcType = JdbcType.VARCHAR),
            @Result(column = "url_hls_hd", property = "urlHlsHd", jdbcType = JdbcType.VARCHAR),
            @Result(column = "rtmp", property = "rtmp", jdbcType = JdbcType.VARCHAR),
            @Result(column = "rtmp_hd", property = "rtmpHd", jdbcType = JdbcType.VARCHAR),
            @Result(column = "ws_addr", property = "wsAddr", jdbcType = JdbcType.VARCHAR),
            @Result(column = "ias_id", property = "iasId", jdbcType = JdbcType.INTEGER),
            @Result(column = "farmland_id", property = "farmlandId", jdbcType = JdbcType.INTEGER),
            @Result(column = "area_id", property = "areaId", jdbcType = JdbcType.INTEGER),
            @Result(column = "location", property = "location", jdbcType = JdbcType.INTEGER),
            @Result(column = "capability", property = "capability", jdbcType = JdbcType.OTHER)
    })
    CameraDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera
     *
     * @mbg.generated
     */
    @UpdateProvider(type = CameraDOSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CameraDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera
     *
     * @mbg.generated
     */
    @Update({
            "update camera",
            "set name = #{name,jdbcType=VARCHAR},",
            "sn = #{sn,jdbcType=VARCHAR},",
            "code = #{code,jdbcType=VARCHAR},",
            "url_hls = #{urlHls,jdbcType=VARCHAR},",
            "url_hls_hd = #{urlHlsHd,jdbcType=VARCHAR},",
            "rtmp = #{rtmp,jdbcType=VARCHAR},",
            "rtmp_hd = #{rtmpHd,jdbcType=VARCHAR},",
            "ws_addr = #{wsAddr,jdbcType=VARCHAR},",
            "ias_id = #{iasId,jdbcType=INTEGER},",
            "farmland_id = #{farmlandId,jdbcType=INTEGER},",
            "area_id = #{areaId,jdbcType=INTEGER},",
            "location = #{location,jdbcType=INTEGER},",
            "capability = #{capability,jdbcType=OTHER}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CameraDO record);
}