package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.CommonCropDO;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface CommonCropDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    @Delete({
        "delete from common_crop_cat",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    @Insert({
        "insert into common_crop_cat (id, name, ",
        "is_show, create_time, ",
        "update_time, sort)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{is_show,jdbcType=BIT}, #{create_time,jdbcType=TIMESTAMP}, ",
        "#{update_time,jdbcType=TIMESTAMP}, #{sort,jdbcType=INTEGER})"
    })
    int insert(CommonCropDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    @InsertProvider(type=CommonCropDOSqlProvider.class, method="insertSelective")
    int insertSelective(CommonCropDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, is_show, create_time, update_time, sort",
        "from common_crop_cat",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_show", property="is_show", jdbcType=JdbcType.BIT),
        @Result(column="create_time", property="create_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="update_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER)
    })
    CommonCropDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommonCropDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CommonCropDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    @Update({
        "update common_crop_cat",
        "set name = #{name,jdbcType=VARCHAR},",
          "is_show = #{is_show,jdbcType=BIT},",
          "create_time = #{create_time,jdbcType=TIMESTAMP},",
          "update_time = #{update_time,jdbcType=TIMESTAMP},",
          "sort = #{sort,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CommonCropDO record);
}