package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.CommonCropDO;
import org.apache.ibatis.jdbc.SQL;

public class CommonCropDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    public String insertSelective(CommonCropDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("common_crop_cat");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIs_show() != null) {
            sql.VALUES("is_show", "#{is_show,jdbcType=BIT}");
        }
        
        if (record.getCreate_time() != null) {
            sql.VALUES("create_time", "#{create_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdate_time() != null) {
            sql.VALUES("update_time", "#{update_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSort() != null) {
            sql.VALUES("sort", "#{sort,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_crop_cat
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(CommonCropDO record) {
        SQL sql = new SQL();
        sql.UPDATE("common_crop_cat");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIs_show() != null) {
            sql.SET("is_show = #{is_show,jdbcType=BIT}");
        }
        
        if (record.getCreate_time() != null) {
            sql.SET("create_time = #{create_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdate_time() != null) {
            sql.SET("update_time = #{update_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSort() != null) {
            sql.SET("sort = #{sort,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}