package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.ControllerStatusRecord;
import org.apache.ibatis.jdbc.SQL;

public class ControllerStatusRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table controller_status_log
     *
     * @mbg.generated
     */
    public String insertSelective(ControllerStatusRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("controller_status_log");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }

        if (record.getDeviceId() != null) {
            sql.VALUES("device_id", "#{deviceId,jdbcType=BIGINT}");
        }

        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }

        if (record.getBatteryVol() != null) {
            sql.VALUES("battery_vol", "#{batteryVol,jdbcType=INTEGER}");
        }

        if (record.getBatteryWithSolarVol() != null) {
            sql.VALUES("battery_with_solar_vol", "#{batteryWithSolarVol,jdbcType=INTEGER}");
        }

        if (record.getSolarPanelVol() != null) {
            sql.VALUES("solar_panel_vol", "#{solarPanelVol,jdbcType=INTEGER}");
        }

        if (record.getSignalStrength() != null) {
            sql.VALUES("signal_strength", "#{signalStrength,jdbcType=INTEGER}");
        }

        if (record.getBoardTemp() != null) {
            sql.VALUES("board_temp", "#{boardTemp,jdbcType=INTEGER}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table controller_status_log
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(ControllerStatusRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("controller_status_log");

        if (record.getDeviceId() != null) {
            sql.SET("device_id = #{deviceId,jdbcType=BIGINT}");
        }

        if (record.getTime() != null) {
            sql.SET("time = #{time,jdbcType=TIMESTAMP}");
        }

        if (record.getBatteryVol() != null) {
            sql.SET("battery_vol = #{batteryVol,jdbcType=INTEGER}");
        }

        if (record.getBatteryWithSolarVol() != null) {
            sql.SET("battery_with_solar_vol = #{batteryWithSolarVol,jdbcType=INTEGER}");
        }

        if (record.getSolarPanelVol() != null) {
            sql.SET("solar_panel_vol = #{solarPanelVol,jdbcType=INTEGER}");
        }

        if (record.getSignalStrength() != null) {
            sql.SET("signal_strength = #{signalStrength,jdbcType=INTEGER}");
        }

        if (record.getBoardTemp() != null) {
            sql.SET("board_temp = #{boardTemp,jdbcType=INTEGER}");
        }

        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }
}