package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.DeviceStatusDO;
import org.apache.ibatis.jdbc.SQL;

public class DeviceStatusDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    public String insertSelective(DeviceStatusDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("device_status");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getDevId() != null) {
            sql.VALUES("dev_id", "#{devId,jdbcType=BIGINT}");
        }
        
        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOldState() != null) {
            sql.VALUES("old_state", "#{oldState,jdbcType=INTEGER}");
        }
        
        if (record.getNewState() != null) {
            sql.VALUES("new_state", "#{newState,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(DeviceStatusDO record) {
        SQL sql = new SQL();
        sql.UPDATE("device_status");
        
        if (record.getDevId() != null) {
            sql.SET("dev_id = #{devId,jdbcType=BIGINT}");
        }
        
        if (record.getTime() != null) {
            sql.SET("time = #{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOldState() != null) {
            sql.SET("old_state = #{oldState,jdbcType=INTEGER}");
        }
        
        if (record.getNewState() != null) {
            sql.SET("new_state = #{newState,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}