package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.DeviceOperateDO;
import org.apache.ibatis.jdbc.SQL;

public class DeviceOperateDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    public String insertSelective(DeviceOperateDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("device_operate");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getIasDevId() != null) {
            sql.VALUES("ias_dev_id", "#{iasDevId,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOpType() != null) {
            sql.VALUES("op_type", "#{opType,jdbcType=INTEGER}");
        }
        
        if (record.getAutoStop() != null) {
            sql.VALUES("auto_stop", "#{autoStop,jdbcType=BIT}");
        }
        
        if (record.getDuration() != null) {
            sql.VALUES("duration", "#{duration,jdbcType=INTEGER}");
        }
        
        if (record.getParam() != null) {
            sql.VALUES("param", "#{param,jdbcType=INTEGER}");
        }
        
        if (record.getResult() != null) {
            sql.VALUES("result", "#{result,jdbcType=INTEGER}");
        }
        
        if (record.getSource() != null) {
            sql.VALUES("source", "#{source,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(DeviceOperateDO record) {
        SQL sql = new SQL();
        sql.UPDATE("device_operate");
        
        if (record.getIasDevId() != null) {
            sql.SET("ias_dev_id = #{iasDevId,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            sql.SET("time = #{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOpType() != null) {
            sql.SET("op_type = #{opType,jdbcType=INTEGER}");
        }
        
        if (record.getAutoStop() != null) {
            sql.SET("auto_stop = #{autoStop,jdbcType=BIT}");
        }
        
        if (record.getDuration() != null) {
            sql.SET("duration = #{duration,jdbcType=INTEGER}");
        }
        
        if (record.getParam() != null) {
            sql.SET("param = #{param,jdbcType=INTEGER}");
        }
        
        if (record.getResult() != null) {
            sql.SET("result = #{result,jdbcType=INTEGER}");
        }
        
        if (record.getSource() != null) {
            sql.SET("source = #{source,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}