package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.DeviceStatusDO;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DeviceStatusDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @Delete({
        "delete from device_status",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @Insert({
        "insert into device_status (id, dev_id, ",
        "time, old_state, ",
        "new_state)",
        "values (#{id,jdbcType=BIGINT}, #{devId,jdbcType=BIGINT}, ",
        "#{time,jdbcType=TIMESTAMP}, #{oldState,jdbcType=INTEGER}, ",
        "#{newState,jdbcType=INTEGER})"
    })
    int insert(DeviceStatusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @InsertProvider(type=DeviceStatusDOSqlProvider.class, method="insertSelective")
    int insertSelective(DeviceStatusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, dev_id, time, old_state, new_state",
        "from device_status",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dev_id", property="devId", jdbcType=JdbcType.BIGINT),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="old_state", property="oldState", jdbcType=JdbcType.INTEGER),
        @Result(column="new_state", property="newState", jdbcType=JdbcType.INTEGER)
    })
    DeviceStatusDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @UpdateProvider(type=DeviceStatusDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DeviceStatusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @Update({
        "update device_status",
        "set dev_id = #{devId,jdbcType=BIGINT},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "old_state = #{oldState,jdbcType=INTEGER},",
          "new_state = #{newState,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(DeviceStatusDO record);
}