package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.DeviceOperateDO;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DeviceOperateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    @Delete({
        "delete from device_operate",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    @Insert({
        "insert into device_operate (id, ias_dev_id, ",
        "time, op_type, ",
        "auto_stop, duration, ",
        "param, result, source, ",
        "user_id)",
        "values (#{id,jdbcType=BIGINT}, #{iasDevId,jdbcType=INTEGER}, ",
        "#{time,jdbcType=TIMESTAMP}, #{opType,jdbcType=INTEGER}, ",
        "#{autoStop,jdbcType=BIT}, #{duration,jdbcType=INTEGER}, ",
        "#{param,jdbcType=INTEGER}, #{result,jdbcType=INTEGER}, #{source,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER})"
    })
    int insert(DeviceOperateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    @InsertProvider(type=DeviceOperateDOSqlProvider.class, method="insertSelective")
    int insertSelective(DeviceOperateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, ias_dev_id, time, op_type, auto_stop, duration, param, result, source, user_id",
        "from device_operate",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ias_dev_id", property="iasDevId", jdbcType=JdbcType.INTEGER),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="op_type", property="opType", jdbcType=JdbcType.INTEGER),
        @Result(column="auto_stop", property="autoStop", jdbcType=JdbcType.BIT),
        @Result(column="duration", property="duration", jdbcType=JdbcType.INTEGER),
        @Result(column="param", property="param", jdbcType=JdbcType.INTEGER),
        @Result(column="result", property="result", jdbcType=JdbcType.INTEGER),
        @Result(column="source", property="source", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER)
    })
    DeviceOperateDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    @UpdateProvider(type=DeviceOperateDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DeviceOperateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_operate
     *
     * @mbg.generated
     */
    @Update({
        "update device_operate",
        "set ias_dev_id = #{iasDevId,jdbcType=INTEGER},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "op_type = #{opType,jdbcType=INTEGER},",
          "auto_stop = #{autoStop,jdbcType=BIT},",
          "duration = #{duration,jdbcType=INTEGER},",
          "param = #{param,jdbcType=INTEGER},",
          "result = #{result,jdbcType=INTEGER},",
          "source = #{source,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(DeviceOperateDO record);
}