package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.IasDeviceRecord;
import org.apache.ibatis.jdbc.SQL;

public class IasDeviceRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ias_device
     *
     * @mbg.generated
     */
    public String insertSelective(IasDeviceRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("ias_device");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }

        if (record.getDevId() != null) {
            sql.VALUES("dev_id", "#{devId,jdbcType=BIGINT}");
        }

        if (record.getIasId() != null) {
            sql.VALUES("ias_id", "#{iasId,jdbcType=INTEGER}");
        }

        if (record.getFarmlandId() != null) {
            sql.VALUES("farmland_id", "#{farmlandId,jdbcType=INTEGER}");
        }

        if (record.getIrriAreaId() != null) {
            sql.VALUES("irri_area_id", "#{irriAreaId,jdbcType=INTEGER}");
        }

        if (record.getIasDevId() != null) {
            sql.VALUES("ias_dev_id", "#{iasDevId,jdbcType=BIGINT}");
        }

        if (record.getIrriFerId() != null) {
            sql.VALUES("irri_fer_id", "#{irriFerId,jdbcType=INTEGER}");
        }

        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }

        if (record.getUsageType() != null) {
            sql.VALUES("usage_type", "#{usageType,jdbcType=INTEGER}");
        }

        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }

        if (record.getSortOrder() != null) {
            sql.VALUES("sort_order", "#{sortOrder,jdbcType=INTEGER}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ias_device
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(IasDeviceRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("ias_device");

        if (record.getDevId() != null) {
            sql.SET("dev_id = #{devId,jdbcType=BIGINT}");
        }

        if (record.getIasId() != null) {
            sql.SET("ias_id = #{iasId,jdbcType=INTEGER}");
        }

        if (record.getFarmlandId() != null) {
            sql.SET("farmland_id = #{farmlandId,jdbcType=INTEGER}");
        }

        if (record.getIrriAreaId() != null) {
            sql.SET("irri_area_id = #{irriAreaId,jdbcType=INTEGER}");
        }

        if (record.getIasDevId() != null) {
            sql.SET("ias_dev_id = #{iasDevId,jdbcType=BIGINT}");
        }

        if (record.getIrriFerId() != null) {
            sql.SET("irri_fer_id = #{irriFerId,jdbcType=INTEGER}");
        }

        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }

        if (record.getUsageType() != null) {
            sql.SET("usage_type = #{usageType,jdbcType=INTEGER}");
        }

        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }

        if (record.getSortOrder() != null) {
            sql.SET("sort_order = #{sortOrder,jdbcType=INTEGER}");
        }

        sql.WHERE("id = #{id,jdbcType=INTEGER}");

        return sql.toString();
    }
}