package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoArticleReportDO;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface InfoArticleReportDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    @Delete({
        "delete from info_article_report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    @Insert({
        "insert into info_article_report (id, userId, ",
        "articleId, reason)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{articleId,jdbcType=INTEGER}, #{reason,jdbcType=VARCHAR})"
    })
    int insert(InfoArticleReportDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    @InsertProvider(type=InfoArticleReportDOSqlProvider.class, method="insertSelective")
    int insertSelective(InfoArticleReportDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userId, articleId, reason",
        "from info_article_report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="articleId", property="articleId", jdbcType=JdbcType.INTEGER),
        @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR)
    })
    InfoArticleReportDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    @UpdateProvider(type=InfoArticleReportDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InfoArticleReportDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    @Update({
        "update info_article_report",
        "set userId = #{userId,jdbcType=INTEGER},",
          "articleId = #{articleId,jdbcType=INTEGER},",
          "reason = #{reason,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(InfoArticleReportDO record);
}