package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoCatDO;
import org.apache.ibatis.jdbc.SQL;

public class InfoCatDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_cat
     *
     * @mbg.generated
     */
    public String insertSelective(InfoCatDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("info_cat");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=SMALLINT}");
        }
        
        if (record.getPid() != null) {
            sql.VALUES("pid", "#{pid,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_cat
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(InfoCatDO record) {
        SQL sql = new SQL();
        sql.UPDATE("info_cat");
        
        if (record.getPid() != null) {
            sql.SET("pid = #{pid,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=SMALLINT}");
        
        return sql.toString();
    }
}