package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoSubjectCatArticleDO;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface InfoSubjectCatArticleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @Delete({
        "delete from info_subject_cat_article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @Insert({
        "insert into info_subject_cat_article (id, subjectId, ",
        "subjectCatId, articleId)",
        "values (#{id,jdbcType=INTEGER}, #{subjectId,jdbcType=SMALLINT}, ",
        "#{subjectCatId,jdbcType=SMALLINT}, #{articleId,jdbcType=INTEGER})"
    })
    int insert(InfoSubjectCatArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @InsertProvider(type=InfoSubjectCatArticleDOSqlProvider.class, method="insertSelective")
    int insertSelective(InfoSubjectCatArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, subjectId, subjectCatId, articleId",
        "from info_subject_cat_article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="subjectId", property="subjectId", jdbcType=JdbcType.SMALLINT),
        @Result(column="subjectCatId", property="subjectCatId", jdbcType=JdbcType.SMALLINT),
        @Result(column="articleId", property="articleId", jdbcType=JdbcType.INTEGER)
    })
    InfoSubjectCatArticleDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @UpdateProvider(type=InfoSubjectCatArticleDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InfoSubjectCatArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @Update({
        "update info_subject_cat_article",
        "set subjectId = #{subjectId,jdbcType=SMALLINT},",
          "subjectCatId = #{subjectCatId,jdbcType=SMALLINT},",
          "articleId = #{articleId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(InfoSubjectCatArticleDO record);
}