package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoSubjectCatDO;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface InfoSubjectCatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    @Delete({
        "delete from info_subject_cat",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    @Insert({
        "insert into info_subject_cat (id, name, ",
        "subjectId)",
        "values (#{id,jdbcType=SMALLINT}, #{name,jdbcType=VARCHAR}, ",
        "#{subjectId,jdbcType=SMALLINT})"
    })
    int insert(InfoSubjectCatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    @InsertProvider(type=InfoSubjectCatDOSqlProvider.class, method="insertSelective")
    int insertSelective(InfoSubjectCatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, subjectId",
        "from info_subject_cat",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="subjectId", property="subjectId", jdbcType=JdbcType.SMALLINT)
    })
    InfoSubjectCatDO selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    @UpdateProvider(type=InfoSubjectCatDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InfoSubjectCatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    @Update({
        "update info_subject_cat",
        "set name = #{name,jdbcType=VARCHAR},",
          "subjectId = #{subjectId,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(InfoSubjectCatDO record);
}