package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoSubjectCatDO;
import org.apache.ibatis.jdbc.SQL;

public class InfoSubjectCatDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    public String insertSelective(InfoSubjectCatDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("info_subject_cat");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=SMALLINT}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSubjectId() != null) {
            sql.VALUES("subjectId", "#{subjectId,jdbcType=SMALLINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(InfoSubjectCatDO record) {
        SQL sql = new SQL();
        sql.UPDATE("info_subject_cat");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSubjectId() != null) {
            sql.SET("subjectId = #{subjectId,jdbcType=SMALLINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=SMALLINT}");
        
        return sql.toString();
    }
}