package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoSubjectDO;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface InfoSubjectDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @Delete({
        "delete from info_subject",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @Insert({
        "insert into info_subject (id, title, ",
        "img, originImg, ",
        "watchCount, commentCount, ",
        "publishTime, summary, ",
        "origin)",
        "values (#{id,jdbcType=SMALLINT}, #{title,jdbcType=VARCHAR}, ",
        "#{img,jdbcType=VARCHAR}, #{originImg,jdbcType=VARCHAR}, ",
        "#{watchCount,jdbcType=SMALLINT}, #{commentCount,jdbcType=SMALLINT}, ",
        "#{publishTime,jdbcType=TIMESTAMP}, #{summary,jdbcType=VARCHAR}, ",
        "#{origin,jdbcType=VARCHAR})"
    })
    int insert(InfoSubjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @InsertProvider(type=InfoSubjectDOSqlProvider.class, method="insertSelective")
    int insertSelective(InfoSubjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, title, img, originImg, watchCount, commentCount, publishTime, summary, origin",
        "from info_subject",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="originImg", property="originImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="watchCount", property="watchCount", jdbcType=JdbcType.SMALLINT),
        @Result(column="commentCount", property="commentCount", jdbcType=JdbcType.SMALLINT),
        @Result(column="publishTime", property="publishTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="summary", property="summary", jdbcType=JdbcType.VARCHAR),
        @Result(column="origin", property="origin", jdbcType=JdbcType.VARCHAR)
    })
    InfoSubjectDO selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @UpdateProvider(type=InfoSubjectDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InfoSubjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @Update({
        "update info_subject",
        "set title = #{title,jdbcType=VARCHAR},",
          "img = #{img,jdbcType=VARCHAR},",
          "originImg = #{originImg,jdbcType=VARCHAR},",
          "watchCount = #{watchCount,jdbcType=SMALLINT},",
          "commentCount = #{commentCount,jdbcType=SMALLINT},",
          "publishTime = #{publishTime,jdbcType=TIMESTAMP},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "origin = #{origin,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(InfoSubjectDO record);
}