package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoArticleReportDO;
import org.apache.ibatis.jdbc.SQL;

public class InfoArticleReportDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    public String insertSelective(InfoArticleReportDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("info_article_report");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getArticleId() != null) {
            sql.VALUES("articleId", "#{articleId,jdbcType=INTEGER}");
        }
        
        if (record.getReason() != null) {
            sql.VALUES("reason", "#{reason,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article_report
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(InfoArticleReportDO record) {
        SQL sql = new SQL();
        sql.UPDATE("info_article_report");
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getArticleId() != null) {
            sql.SET("articleId = #{articleId,jdbcType=INTEGER}");
        }
        
        if (record.getReason() != null) {
            sql.SET("reason = #{reason,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}