package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoSubjectCatArticleDO;
import org.apache.ibatis.jdbc.SQL;

public class InfoSubjectCatArticleDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    public String insertSelective(InfoSubjectCatArticleDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("info_subject_cat_article");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSubjectId() != null) {
            sql.VALUES("subjectId", "#{subjectId,jdbcType=SMALLINT}");
        }
        
        if (record.getSubjectCatId() != null) {
            sql.VALUES("subjectCatId", "#{subjectCatId,jdbcType=SMALLINT}");
        }
        
        if (record.getArticleId() != null) {
            sql.VALUES("articleId", "#{articleId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(InfoSubjectCatArticleDO record) {
        SQL sql = new SQL();
        sql.UPDATE("info_subject_cat_article");
        
        if (record.getSubjectId() != null) {
            sql.SET("subjectId = #{subjectId,jdbcType=SMALLINT}");
        }
        
        if (record.getSubjectCatId() != null) {
            sql.SET("subjectCatId = #{subjectCatId,jdbcType=SMALLINT}");
        }
        
        if (record.getArticleId() != null) {
            sql.SET("articleId = #{articleId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}