package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoCommentLikeDO;
import org.apache.ibatis.jdbc.SQL;

public class InfoCommentLikeDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_comment_like
     *
     * @mbg.generated
     */
    public String insertSelective(InfoCommentLikeDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("info_comment_like");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getCommentId() != null) {
            sql.VALUES("commentId", "#{commentId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_comment_like
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(InfoCommentLikeDO record) {
        SQL sql = new SQL();
        sql.UPDATE("info_comment_like");
        
        if (record.getCommentId() != null) {
            sql.SET("commentId = #{commentId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{userId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}