package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.InfoArticleDO;
import org.apache.ibatis.jdbc.SQL;

public class InfoArticleDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article
     *
     * @mbg.generated
     */
    public String insertSelective(InfoArticleDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("info_article");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getImg() != null) {
            sql.VALUES("img", "#{img,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginImg() != null) {
            sql.VALUES("originImg", "#{originImg,jdbcType=VARCHAR}");
        }
        
        if (record.getWatchCount() != null) {
            sql.VALUES("watchCount", "#{watchCount,jdbcType=SMALLINT}");
        }
        
        if (record.getCommentCount() != null) {
            sql.VALUES("commentCount", "#{commentCount,jdbcType=SMALLINT}");
        }
        
        if (record.getPublishTime() != null) {
            sql.VALUES("publishTime", "#{publishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTag() != null) {
            sql.VALUES("tag", "#{tag,jdbcType=VARCHAR}");
        }
        
        if (record.getOrigin() != null) {
            sql.VALUES("origin", "#{origin,jdbcType=VARCHAR}");
        }
        
        if (record.getRegionId() != null) {
            sql.VALUES("regionId", "#{regionId,jdbcType=SMALLINT}");
        }
        
        if (record.getCropId() != null) {
            sql.VALUES("cropId", "#{cropId,jdbcType=INTEGER}");
        }
        
        if (record.getCatPid() != null) {
            sql.VALUES("catPid", "#{catPid,jdbcType=VARCHAR}");
        }
        
        if (record.getCatId() != null) {
            sql.VALUES("catId", "#{catId,jdbcType=SMALLINT}");
        }
        
        if (record.getHtmlContent() != null) {
            sql.VALUES("htmlContent", "#{htmlContent,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_article
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(InfoArticleDO record) {
        SQL sql = new SQL();
        sql.UPDATE("info_article");
        
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getImg() != null) {
            sql.SET("img = #{img,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginImg() != null) {
            sql.SET("originImg = #{originImg,jdbcType=VARCHAR}");
        }
        
        if (record.getWatchCount() != null) {
            sql.SET("watchCount = #{watchCount,jdbcType=SMALLINT}");
        }
        
        if (record.getCommentCount() != null) {
            sql.SET("commentCount = #{commentCount,jdbcType=SMALLINT}");
        }
        
        if (record.getPublishTime() != null) {
            sql.SET("publishTime = #{publishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getTag() != null) {
            sql.SET("tag = #{tag,jdbcType=VARCHAR}");
        }
        
        if (record.getOrigin() != null) {
            sql.SET("origin = #{origin,jdbcType=VARCHAR}");
        }
        
        if (record.getRegionId() != null) {
            sql.SET("regionId = #{regionId,jdbcType=SMALLINT}");
        }
        
        if (record.getCropId() != null) {
            sql.SET("cropId = #{cropId,jdbcType=INTEGER}");
        }
        
        if (record.getCatPid() != null) {
            sql.SET("catPid = #{catPid,jdbcType=VARCHAR}");
        }
        
        if (record.getCatId() != null) {
            sql.SET("catId = #{catId,jdbcType=SMALLINT}");
        }
        
        if (record.getHtmlContent() != null) {
            sql.SET("htmlContent = #{htmlContent,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}