package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.IrrigationTaskRecord;
import org.apache.ibatis.jdbc.SQL;

public class IrrigationTaskRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table irrigation_task
     *
     * @mbg.generated
     */
    public String insertSelective(IrrigationTaskRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("irrigation_task");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getIasId() != null) {
            sql.VALUES("ias_id", "#{iasId,jdbcType=INTEGER}");
        }
        
        if (record.getFarmlandId() != null) {
            sql.VALUES("farmland_id", "#{farmlandId,jdbcType=INTEGER}");
        }
        
        if (record.getIrriAreaId() != null) {
            sql.VALUES("irri_area_id", "#{irriAreaId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStartTime() != null) {
            sql.VALUES("start_time", "#{startTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFinishTime() != null) {
            sql.VALUES("finish_time", "#{finishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            sql.VALUES("create_user", "#{createUser,jdbcType=INTEGER}");
        }
        
        if (record.getDeleteUser() != null) {
            sql.VALUES("delete_user", "#{deleteUser,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (record.getResult() != null) {
            sql.VALUES("result", "#{result,jdbcType=INTEGER}");
        }
        
        if (record.getExpDuration() != null) {
            sql.VALUES("exp_duration", "#{expDuration,jdbcType=INTEGER}");
        }
        
        if (record.getIrriDuration() != null) {
            sql.VALUES("irri_duration", "#{irriDuration,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table irrigation_task
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(IrrigationTaskRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("irrigation_task");
        
        if (record.getIasId() != null) {
            sql.SET("ias_id = #{iasId,jdbcType=INTEGER}");
        }
        
        if (record.getFarmlandId() != null) {
            sql.SET("farmland_id = #{farmlandId,jdbcType=INTEGER}");
        }
        
        if (record.getIrriAreaId() != null) {
            sql.SET("irri_area_id = #{irriAreaId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStartTime() != null) {
            sql.SET("start_time = #{startTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFinishTime() != null) {
            sql.SET("finish_time = #{finishTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{createUser,jdbcType=INTEGER}");
        }
        
        if (record.getDeleteUser() != null) {
            sql.SET("delete_user = #{deleteUser,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }
        
        if (record.getResult() != null) {
            sql.SET("result = #{result,jdbcType=INTEGER}");
        }
        
        if (record.getExpDuration() != null) {
            sql.SET("exp_duration = #{expDuration,jdbcType=INTEGER}");
        }
        
        if (record.getIrriDuration() != null) {
            sql.SET("irri_duration = #{irriDuration,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}