package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.MessageUserRecord;
import org.apache.ibatis.jdbc.SQL;

public class MessageUserRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated
     */
    public String insertSelective(MessageUserRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("message_user");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }

        if (record.getMsgId() != null) {
            sql.VALUES("msg_id", "#{msgId,jdbcType=INTEGER}");
        }

        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }

        if (record.getIsRead() != null) {
            sql.VALUES("is_read", "#{isRead,jdbcType=TINYINT}");
        }

        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=TINYINT}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MessageUserRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("message_user");

        if (record.getMsgId() != null) {
            sql.SET("msg_id = #{msgId,jdbcType=INTEGER}");
        }

        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }

        if (record.getIsRead() != null) {
            sql.SET("is_read = #{isRead,jdbcType=TINYINT}");
        }

        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=TINYINT}");
        }

        sql.WHERE("id = #{id,jdbcType=INTEGER}");

        return sql.toString();
    }
}