package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.MessagePushLogRecord;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface MessagePushLogRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_log
     *
     * @mbg.generated
     */
    int insert(MessagePushLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_log
     *
     * @mbg.generated
     */
    int insertSelective(MessagePushLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_log
     *
     * @mbg.generated
     */
    MessagePushLogRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessagePushLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MessagePushLogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessagePushLogRecord record);
}