package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.MessageSysRecord;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MessageSysRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sys
     *
     * @mbg.generated
     */
    @Delete({
        "delete from message_sys",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sys
     *
     * @mbg.generated
     */
    @Insert({
        "insert into message_sys (id, title, ",
        "type, content, url, ",
        "create_time)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=TINYINT}, #{content,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(MessageSysRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sys
     *
     * @mbg.generated
     */
    @InsertProvider(type=MessageSysRecordSqlProvider.class, method="insertSelective")
    int insertSelective(MessageSysRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sys
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, title, type, content, url, create_time",
        "from message_sys",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.TINYINT),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    MessageSysRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sys
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MessageSysRecordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MessageSysRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sys
     *
     * @mbg.generated
     */
    @Update({
        "update message_sys",
        "set title = #{title,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=TINYINT},",
          "content = #{content,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MessageSysRecord record);
}