package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.SysConfigDO;
import org.apache.ibatis.jdbc.SQL;

public class SysConfigDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    public String insertSelective(SysConfigDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("system_config");

        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }

        if (record.getValue() != null) {
            sql.VALUES("value", "#{value,jdbcType=OTHER}");
        }

        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(SysConfigDO record) {
        SQL sql = new SQL();
        sql.UPDATE("system_config");

        if (record.getValue() != null) {
            sql.SET("value = #{value,jdbcType=OTHER}");
        }

        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }

        sql.WHERE("name = #{name,jdbcType=VARCHAR}");

        return sql.toString();
    }
}