package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.SysConfigDO;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface SysConfigDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    @Delete({
            "delete from system_config",
            "where name = #{name,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    @Insert({
            "insert into system_config (name, value, ",
            "description)",
            "values (#{name,jdbcType=VARCHAR}, #{value,jdbcType=OTHER}, ",
            "#{description,jdbcType=VARCHAR})"
    })
    int insert(SysConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    @InsertProvider(type = SysConfigDOSqlProvider.class, method = "insertSelective")
    int insertSelective(SysConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "name, value, description",
            "from system_config",
            "where name = #{name,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR, id = true),
            @Result(column = "value", property = "value", jdbcType = JdbcType.OTHER),
            @Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR)
    })
    SysConfigDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    @UpdateProvider(type = SysConfigDOSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    @Update({
            "update system_config",
            "set value = #{value,jdbcType=OTHER},",
            "description = #{description,jdbcType=VARCHAR}",
            "where name = #{name,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysConfigDO record);
}