package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.UserIasRecord;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface UserIasRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    @Delete({
            "delete from user_ias",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    @Insert({
            "insert into user_ias (id, user_id, ",
            "ias_id, role_id)",
            "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
            "#{iasId,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER})"
    })
    int insert(UserIasRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    @InsertProvider(type = UserIasRecordSqlProvider.class, method = "insertSelective")
    int insertSelective(UserIasRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, user_id, ias_id, role_id",
            "from user_ias",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
            @Result(column = "ias_id", property = "iasId", jdbcType = JdbcType.INTEGER),
            @Result(column = "role_id", property = "roleId", jdbcType = JdbcType.INTEGER)
    })
    UserIasRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    @UpdateProvider(type = UserIasRecordSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserIasRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    @Update({
            "update user_ias",
            "set user_id = #{userId,jdbcType=INTEGER},",
            "ias_id = #{iasId,jdbcType=INTEGER},",
            "role_id = #{roleId,jdbcType=INTEGER}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserIasRecord record);
}