package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.UserMessageDO;
import com.zzwl.ias.domain.UserMessageDOKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserMessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    @Delete({
        "delete from user_message",
        "where user_id = #{userId,jdbcType=INTEGER}",
          "and msg_id = #{msgId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(UserMessageDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    @Insert({
        "insert into user_message (user_id, msg_id, ",
        "verified, read_time)",
        "values (#{userId,jdbcType=INTEGER}, #{msgId,jdbcType=BIGINT}, ",
        "#{verified,jdbcType=BIT}, #{readTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    @InsertProvider(type=UserMessageDOSqlProvider.class, method="insertSelective")
    int insertSelective(UserMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "user_id, msg_id, verified, read_time",
        "from user_message",
        "where user_id = #{userId,jdbcType=INTEGER}",
          "and msg_id = #{msgId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="msg_id", property="msgId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="verified", property="verified", jdbcType=JdbcType.BIT),
        @Result(column="read_time", property="readTime", jdbcType=JdbcType.TIMESTAMP)
    })
    UserMessageDO selectByPrimaryKey(UserMessageDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserMessageDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    @Update({
        "update user_message",
        "set verified = #{verified,jdbcType=BIT},",
          "read_time = #{readTime,jdbcType=TIMESTAMP}",
        "where user_id = #{userId,jdbcType=INTEGER}",
          "and msg_id = #{msgId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserMessageDO record);
}