package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.UserIasRecord;
import org.apache.ibatis.jdbc.SQL;

public class UserIasRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    public String insertSelective(UserIasRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_ias");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }

        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }

        if (record.getIasId() != null) {
            sql.VALUES("ias_id", "#{iasId,jdbcType=INTEGER}");
        }

        if (record.getRoleId() != null) {
            sql.VALUES("role_id", "#{roleId,jdbcType=INTEGER}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ias
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UserIasRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("user_ias");

        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }

        if (record.getIasId() != null) {
            sql.SET("ias_id = #{iasId,jdbcType=INTEGER}");
        }

        if (record.getRoleId() != null) {
            sql.SET("role_id = #{roleId,jdbcType=INTEGER}");
        }

        sql.WHERE("id = #{id,jdbcType=INTEGER}");

        return sql.toString();
    }
}