package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.UserMessageDO;
import org.apache.ibatis.jdbc.SQL;

public class UserMessageDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    public String insertSelective(UserMessageDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_message");
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getMsgId() != null) {
            sql.VALUES("msg_id", "#{msgId,jdbcType=BIGINT}");
        }
        
        if (record.getVerified() != null) {
            sql.VALUES("verified", "#{verified,jdbcType=BIT}");
        }
        
        if (record.getReadTime() != null) {
            sql.VALUES("read_time", "#{readTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UserMessageDO record) {
        SQL sql = new SQL();
        sql.UPDATE("user_message");
        
        if (record.getVerified() != null) {
            sql.SET("verified = #{verified,jdbcType=BIT}");
        }
        
        if (record.getReadTime() != null) {
            sql.SET("read_time = #{readTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("user_id = #{userId,jdbcType=INTEGER}");
        sql.WHERE("msg_id = #{msgId,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}