package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.VerificationRecord;
import com.zzwl.ias.domain.VerificationRecordKey;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface VerificationRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VerificationRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_record
     *
     * @mbg.generated
     */
    int insert(VerificationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_record
     *
     * @mbg.generated
     */
    int insertSelective(VerificationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_record
     *
     * @mbg.generated
     */
    VerificationRecord selectByPrimaryKey(VerificationRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VerificationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VerificationRecord record);

    int upsert(VerificationRecord record);
}