package com.zzwl.ias.mapper;

import com.zzwl.ias.domain.WstationIasRecord;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface WstationIasRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    int insert(WstationIasRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    int insertSelective(WstationIasRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    WstationIasRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WstationIasRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WstationIasRecord record);

    Integer selectStaionIdByIasId(int iasId);
}