package com.zzwl.ias.domain;

import java.util.Date;

public class AlarmThresholdRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.sensor_id
     *
     * @mbg.generated
     */
    private Long sensorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.alarm_type
     *
     * @mbg.generated
     */
    private Integer alarmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.alarm_level
     *
     * @mbg.generated
     */
    private Byte alarmLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.threshold
     *
     * @mbg.generated
     */
    private Integer threshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.occur_time
     *
     * @mbg.generated
     */
    private Date occurTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.end_reason
     *
     * @mbg.generated
     */
    private Integer endReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.id
     *
     * @return the value of alarm_threshold.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.id
     *
     * @param id the value for alarm_threshold.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.sensor_id
     *
     * @return the value of alarm_threshold.sensor_id
     * @mbg.generated
     */
    public Long getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.sensor_id
     *
     * @param sensorId the value for alarm_threshold.sensor_id
     * @mbg.generated
     */
    public void setSensorId(Long sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.data_type
     *
     * @return the value of alarm_threshold.data_type
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.data_type
     *
     * @param dataType the value for alarm_threshold.data_type
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.alarm_type
     *
     * @return the value of alarm_threshold.alarm_type
     * @mbg.generated
     */
    public Integer getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.alarm_type
     *
     * @param alarmType the value for alarm_threshold.alarm_type
     * @mbg.generated
     */
    public void setAlarmType(Integer alarmType) {
        this.alarmType = alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.alarm_level
     *
     * @return the value of alarm_threshold.alarm_level
     * @mbg.generated
     */
    public Byte getAlarmLevel() {
        return alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.alarm_level
     *
     * @param alarmLevel the value for alarm_threshold.alarm_level
     * @mbg.generated
     */
    public void setAlarmLevel(Byte alarmLevel) {
        this.alarmLevel = alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.threshold
     *
     * @return the value of alarm_threshold.threshold
     * @mbg.generated
     */
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.threshold
     *
     * @param threshold the value for alarm_threshold.threshold
     * @mbg.generated
     */
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.status
     *
     * @return the value of alarm_threshold.status
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.status
     *
     * @param status the value for alarm_threshold.status
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.occur_time
     *
     * @return the value of alarm_threshold.occur_time
     * @mbg.generated
     */
    public Date getOccurTime() {
        return occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.occur_time
     *
     * @param occurTime the value for alarm_threshold.occur_time
     * @mbg.generated
     */
    public void setOccurTime(Date occurTime) {
        this.occurTime = occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.end_reason
     *
     * @return the value of alarm_threshold.end_reason
     * @mbg.generated
     */
    public Integer getEndReason() {
        return endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.end_reason
     *
     * @param endReason the value for alarm_threshold.end_reason
     * @mbg.generated
     */
    public void setEndReason(Integer endReason) {
        this.endReason = endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.end_time
     *
     * @return the value of alarm_threshold.end_time
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.end_time
     *
     * @param endTime the value for alarm_threshold.end_time
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.user_id
     *
     * @return the value of alarm_threshold.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.user_id
     *
     * @param userId the value for alarm_threshold.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_threshold
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AlarmThresholdRecord other = (AlarmThresholdRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getSensorId() == null ? other.getSensorId() == null : this.getSensorId().equals(other.getSensorId()))
                && (this.getDataType() == null ? other.getDataType() == null : this.getDataType().equals(other.getDataType()))
                && (this.getAlarmType() == null ? other.getAlarmType() == null : this.getAlarmType().equals(other.getAlarmType()))
                && (this.getAlarmLevel() == null ? other.getAlarmLevel() == null : this.getAlarmLevel().equals(other.getAlarmLevel()))
                && (this.getThreshold() == null ? other.getThreshold() == null : this.getThreshold().equals(other.getThreshold()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getOccurTime() == null ? other.getOccurTime() == null : this.getOccurTime().equals(other.getOccurTime()))
                && (this.getEndReason() == null ? other.getEndReason() == null : this.getEndReason().equals(other.getEndReason()))
                && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_threshold
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSensorId() == null) ? 0 : getSensorId().hashCode());
        result = prime * result + ((getDataType() == null) ? 0 : getDataType().hashCode());
        result = prime * result + ((getAlarmType() == null) ? 0 : getAlarmType().hashCode());
        result = prime * result + ((getAlarmLevel() == null) ? 0 : getAlarmLevel().hashCode());
        result = prime * result + ((getThreshold() == null) ? 0 : getThreshold().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOccurTime() == null) ? 0 : getOccurTime().hashCode());
        result = prime * result + ((getEndReason() == null) ? 0 : getEndReason().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }
}