package com.zzwl.ias.domain;

public class AlarmConfigRecord extends AlarmConfigRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_config.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_config.forewarn_uplimit
     *
     * @mbg.generated
     */
    private Integer forewarnUplimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_config.forewarn_lowlimit
     *
     * @mbg.generated
     */
    private Integer forewarnLowlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_config.alarmwarn_uplimit
     *
     * @mbg.generated
     */
    private Integer alarmwarnUplimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_config.alarmwarn_lowlimit
     *
     * @mbg.generated
     */
    private Integer alarmwarnLowlimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_config.id
     *
     * @return the value of alarm_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_config.id
     *
     * @param id the value for alarm_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_config.user_id
     *
     * @return the value of alarm_config.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_config.user_id
     *
     * @param userId the value for alarm_config.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_config.forewarn_uplimit
     *
     * @return the value of alarm_config.forewarn_uplimit
     *
     * @mbg.generated
     */
    public Integer getForewarnUplimit() {
        return forewarnUplimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_config.forewarn_uplimit
     *
     * @param forewarnUplimit the value for alarm_config.forewarn_uplimit
     *
     * @mbg.generated
     */
    public void setForewarnUplimit(Integer forewarnUplimit) {
        this.forewarnUplimit = forewarnUplimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_config.forewarn_lowlimit
     *
     * @return the value of alarm_config.forewarn_lowlimit
     *
     * @mbg.generated
     */
    public Integer getForewarnLowlimit() {
        return forewarnLowlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_config.forewarn_lowlimit
     *
     * @param forewarnLowlimit the value for alarm_config.forewarn_lowlimit
     *
     * @mbg.generated
     */
    public void setForewarnLowlimit(Integer forewarnLowlimit) {
        this.forewarnLowlimit = forewarnLowlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_config.alarmwarn_uplimit
     *
     * @return the value of alarm_config.alarmwarn_uplimit
     *
     * @mbg.generated
     */
    public Integer getAlarmwarnUplimit() {
        return alarmwarnUplimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_config.alarmwarn_uplimit
     *
     * @param alarmwarnUplimit the value for alarm_config.alarmwarn_uplimit
     *
     * @mbg.generated
     */
    public void setAlarmwarnUplimit(Integer alarmwarnUplimit) {
        this.alarmwarnUplimit = alarmwarnUplimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_config.alarmwarn_lowlimit
     *
     * @return the value of alarm_config.alarmwarn_lowlimit
     *
     * @mbg.generated
     */
    public Integer getAlarmwarnLowlimit() {
        return alarmwarnLowlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_config.alarmwarn_lowlimit
     *
     * @param alarmwarnLowlimit the value for alarm_config.alarmwarn_lowlimit
     *
     * @mbg.generated
     */
    public void setAlarmwarnLowlimit(Integer alarmwarnLowlimit) {
        this.alarmwarnLowlimit = alarmwarnLowlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_config
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AlarmConfigRecord other = (AlarmConfigRecord) that;
        return (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()))
            && (this.getAlarmTypeId() == null ? other.getAlarmTypeId() == null : this.getAlarmTypeId().equals(other.getAlarmTypeId()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getForewarnUplimit() == null ? other.getForewarnUplimit() == null : this.getForewarnUplimit().equals(other.getForewarnUplimit()))
            && (this.getForewarnLowlimit() == null ? other.getForewarnLowlimit() == null : this.getForewarnLowlimit().equals(other.getForewarnLowlimit()))
            && (this.getAlarmwarnUplimit() == null ? other.getAlarmwarnUplimit() == null : this.getAlarmwarnUplimit().equals(other.getAlarmwarnUplimit()))
            && (this.getAlarmwarnLowlimit() == null ? other.getAlarmwarnLowlimit() == null : this.getAlarmwarnLowlimit().equals(other.getAlarmwarnLowlimit()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_config
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        result = prime * result + ((getAlarmTypeId() == null) ? 0 : getAlarmTypeId().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getForewarnUplimit() == null) ? 0 : getForewarnUplimit().hashCode());
        result = prime * result + ((getForewarnLowlimit() == null) ? 0 : getForewarnLowlimit().hashCode());
        result = prime * result + ((getAlarmwarnUplimit() == null) ? 0 : getAlarmwarnUplimit().hashCode());
        result = prime * result + ((getAlarmwarnLowlimit() == null) ? 0 : getAlarmwarnLowlimit().hashCode());
        return result;
    }
}