package com.zzwl.ias.domain;

public class AlarmThresholdRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.sensor_id
     *
     * @mbg.generated
     */
    private Long sensorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_threshold.data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.sensor_id
     *
     * @return the value of alarm_threshold.sensor_id
     * @mbg.generated
     */
    public Long getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.sensor_id
     *
     * @param sensorId the value for alarm_threshold.sensor_id
     * @mbg.generated
     */
    public void setSensorId(Long sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_threshold.data_type
     *
     * @return the value of alarm_threshold.data_type
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_threshold.data_type
     *
     * @param dataType the value for alarm_threshold.data_type
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_threshold
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AlarmThresholdRecordKey other = (AlarmThresholdRecordKey) that;
        return (this.getSensorId() == null ? other.getSensorId() == null : this.getSensorId().equals(other.getSensorId()))
                && (this.getDataType() == null ? other.getDataType() == null : this.getDataType().equals(other.getDataType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_threshold
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSensorId() == null) ? 0 : getSensorId().hashCode());
        result = prime * result + ((getDataType() == null) ? 0 : getDataType().hashCode());
        return result;
    }
}