package com.zzwl.ias.domain;

import java.util.Date;

public class ControllerStatusRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.device_id
     *
     * @mbg.generated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.battery_vol
     *
     * @mbg.generated
     */
    private Integer batteryVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.battery_with_solar_vol
     *
     * @mbg.generated
     */
    private Integer batteryWithSolarVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.solar_panel_vol
     *
     * @mbg.generated
     */
    private Integer solarPanelVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.signal_strength
     *
     * @mbg.generated
     */
    private Integer signalStrength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controller_status_log.board_temp
     *
     * @mbg.generated
     */
    private Integer boardTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.id
     *
     * @return the value of controller_status_log.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.id
     *
     * @param id the value for controller_status_log.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.device_id
     *
     * @return the value of controller_status_log.device_id
     * @mbg.generated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.device_id
     *
     * @param deviceId the value for controller_status_log.device_id
     * @mbg.generated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.time
     *
     * @return the value of controller_status_log.time
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.time
     *
     * @param time the value for controller_status_log.time
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.battery_vol
     *
     * @return the value of controller_status_log.battery_vol
     * @mbg.generated
     */
    public Integer getBatteryVol() {
        return batteryVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.battery_vol
     *
     * @param batteryVol the value for controller_status_log.battery_vol
     * @mbg.generated
     */
    public void setBatteryVol(Integer batteryVol) {
        this.batteryVol = batteryVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.battery_with_solar_vol
     *
     * @return the value of controller_status_log.battery_with_solar_vol
     * @mbg.generated
     */
    public Integer getBatteryWithSolarVol() {
        return batteryWithSolarVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.battery_with_solar_vol
     *
     * @param batteryWithSolarVol the value for controller_status_log.battery_with_solar_vol
     * @mbg.generated
     */
    public void setBatteryWithSolarVol(Integer batteryWithSolarVol) {
        this.batteryWithSolarVol = batteryWithSolarVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.solar_panel_vol
     *
     * @return the value of controller_status_log.solar_panel_vol
     * @mbg.generated
     */
    public Integer getSolarPanelVol() {
        return solarPanelVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.solar_panel_vol
     *
     * @param solarPanelVol the value for controller_status_log.solar_panel_vol
     * @mbg.generated
     */
    public void setSolarPanelVol(Integer solarPanelVol) {
        this.solarPanelVol = solarPanelVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.signal_strength
     *
     * @return the value of controller_status_log.signal_strength
     * @mbg.generated
     */
    public Integer getSignalStrength() {
        return signalStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.signal_strength
     *
     * @param signalStrength the value for controller_status_log.signal_strength
     * @mbg.generated
     */
    public void setSignalStrength(Integer signalStrength) {
        this.signalStrength = signalStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controller_status_log.board_temp
     *
     * @return the value of controller_status_log.board_temp
     * @mbg.generated
     */
    public Integer getBoardTemp() {
        return boardTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controller_status_log.board_temp
     *
     * @param boardTemp the value for controller_status_log.board_temp
     * @mbg.generated
     */
    public void setBoardTemp(Integer boardTemp) {
        this.boardTemp = boardTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table controller_status_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ControllerStatusRecord other = (ControllerStatusRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getDeviceId() == null ? other.getDeviceId() == null : this.getDeviceId().equals(other.getDeviceId()))
                && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
                && (this.getBatteryVol() == null ? other.getBatteryVol() == null : this.getBatteryVol().equals(other.getBatteryVol()))
                && (this.getBatteryWithSolarVol() == null ? other.getBatteryWithSolarVol() == null : this.getBatteryWithSolarVol().equals(other.getBatteryWithSolarVol()))
                && (this.getSolarPanelVol() == null ? other.getSolarPanelVol() == null : this.getSolarPanelVol().equals(other.getSolarPanelVol()))
                && (this.getSignalStrength() == null ? other.getSignalStrength() == null : this.getSignalStrength().equals(other.getSignalStrength()))
                && (this.getBoardTemp() == null ? other.getBoardTemp() == null : this.getBoardTemp().equals(other.getBoardTemp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table controller_status_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeviceId() == null) ? 0 : getDeviceId().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getBatteryVol() == null) ? 0 : getBatteryVol().hashCode());
        result = prime * result + ((getBatteryWithSolarVol() == null) ? 0 : getBatteryWithSolarVol().hashCode());
        result = prime * result + ((getSolarPanelVol() == null) ? 0 : getSolarPanelVol().hashCode());
        result = prime * result + ((getSignalStrength() == null) ? 0 : getSignalStrength().hashCode());
        result = prime * result + ((getBoardTemp() == null) ? 0 : getBoardTemp().hashCode());
        return result;
    }
}