package com.zzwl.ias.domain;

import java.util.Date;

public class DataCollectionRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collections.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collections.sensor_id
     *
     * @mbg.generated
     */
    private Long sensorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collections.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collections.value
     *
     * @mbg.generated
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collections.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collections.collection_type
     *
     * @mbg.generated
     */
    private Integer collectionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collections.id
     *
     * @return the value of data_collections.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collections.id
     *
     * @param id the value for data_collections.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collections.sensor_id
     *
     * @return the value of data_collections.sensor_id
     *
     * @mbg.generated
     */
    public Long getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collections.sensor_id
     *
     * @param sensorId the value for data_collections.sensor_id
     *
     * @mbg.generated
     */
    public void setSensorId(Long sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collections.type
     *
     * @return the value of data_collections.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collections.type
     *
     * @param type the value for data_collections.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collections.value
     *
     * @return the value of data_collections.value
     *
     * @mbg.generated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collections.value
     *
     * @param value the value for data_collections.value
     *
     * @mbg.generated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collections.time
     *
     * @return the value of data_collections.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collections.time
     *
     * @param time the value for data_collections.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collections.collection_type
     *
     * @return the value of data_collections.collection_type
     *
     * @mbg.generated
     */
    public Integer getCollectionType() {
        return collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collections.collection_type
     *
     * @param collectionType the value for data_collections.collection_type
     *
     * @mbg.generated
     */
    public void setCollectionType(Integer collectionType) {
        this.collectionType = collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collections
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DataCollectionRecord other = (DataCollectionRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSensorId() == null ? other.getSensorId() == null : this.getSensorId().equals(other.getSensorId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getCollectionType() == null ? other.getCollectionType() == null : this.getCollectionType().equals(other.getCollectionType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collections
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSensorId() == null) ? 0 : getSensorId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getCollectionType() == null) ? 0 : getCollectionType().hashCode());
        return result;
    }
}