package com.zzwl.ias.domain;

public class DcPointRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_point.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_point.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_point.owner_type
     *
     * @mbg.generated
     */
    private Integer ownerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_point.owner_id
     *
     * @mbg.generated
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_point.sensor_id
     *
     * @mbg.generated
     */
    private Long sensorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_point.id
     *
     * @return the value of dc_point.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_point.id
     *
     * @param id the value for dc_point.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_point.name
     *
     * @return the value of dc_point.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_point.name
     *
     * @param name the value for dc_point.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_point.owner_type
     *
     * @return the value of dc_point.owner_type
     * @mbg.generated
     */
    public Integer getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_point.owner_type
     *
     * @param ownerType the value for dc_point.owner_type
     * @mbg.generated
     */
    public void setOwnerType(Integer ownerType) {
        this.ownerType = ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_point.owner_id
     *
     * @return the value of dc_point.owner_id
     * @mbg.generated
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_point.owner_id
     *
     * @param ownerId the value for dc_point.owner_id
     * @mbg.generated
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_point.sensor_id
     *
     * @return the value of dc_point.sensor_id
     * @mbg.generated
     */
    public Long getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_point.sensor_id
     *
     * @param sensorId the value for dc_point.sensor_id
     * @mbg.generated
     */
    public void setSensorId(Long sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_point
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DcPointRecord other = (DcPointRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getOwnerType() == null ? other.getOwnerType() == null : this.getOwnerType().equals(other.getOwnerType()))
                && (this.getOwnerId() == null ? other.getOwnerId() == null : this.getOwnerId().equals(other.getOwnerId()))
                && (this.getSensorId() == null ? other.getSensorId() == null : this.getSensorId().equals(other.getSensorId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_point
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOwnerType() == null) ? 0 : getOwnerType().hashCode());
        result = prime * result + ((getOwnerId() == null) ? 0 : getOwnerId().hashCode());
        result = prime * result + ((getSensorId() == null) ? 0 : getSensorId().hashCode());
        return result;
    }
}