package com.zzwl.ias.domain;

import java.util.Date;

public class DeviceOpRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.source
     *
     * @mbg.generated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.op_type
     *
     * @mbg.generated
     */
    private Byte opType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.auto_stop
     *
     * @mbg.generated
     */
    private Boolean autoStop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.param
     *
     * @mbg.generated
     */
    private Integer param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_op_log.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.id
     *
     * @return the value of dev_op_log.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.id
     *
     * @param id the value for dev_op_log.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.dev_id
     *
     * @return the value of dev_op_log.dev_id
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.dev_id
     *
     * @param devId the value for dev_op_log.dev_id
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.user_id
     *
     * @return the value of dev_op_log.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.user_id
     *
     * @param userId the value for dev_op_log.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.source
     *
     * @return the value of dev_op_log.source
     * @mbg.generated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.source
     *
     * @param source the value for dev_op_log.source
     * @mbg.generated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.time
     *
     * @return the value of dev_op_log.time
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.time
     *
     * @param time the value for dev_op_log.time
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.op_type
     *
     * @return the value of dev_op_log.op_type
     * @mbg.generated
     */
    public Byte getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.op_type
     *
     * @param opType the value for dev_op_log.op_type
     * @mbg.generated
     */
    public void setOpType(Byte opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.auto_stop
     *
     * @return the value of dev_op_log.auto_stop
     * @mbg.generated
     */
    public Boolean getAutoStop() {
        return autoStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.auto_stop
     *
     * @param autoStop the value for dev_op_log.auto_stop
     * @mbg.generated
     */
    public void setAutoStop(Boolean autoStop) {
        this.autoStop = autoStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.duration
     *
     * @return the value of dev_op_log.duration
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.duration
     *
     * @param duration the value for dev_op_log.duration
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.param
     *
     * @return the value of dev_op_log.param
     * @mbg.generated
     */
    public Integer getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.param
     *
     * @param param the value for dev_op_log.param
     * @mbg.generated
     */
    public void setParam(Integer param) {
        this.param = param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_op_log.result
     *
     * @return the value of dev_op_log.result
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_op_log.result
     *
     * @param result the value for dev_op_log.result
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_op_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DeviceOpRecord other = (DeviceOpRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
                && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
                && (this.getOpType() == null ? other.getOpType() == null : this.getOpType().equals(other.getOpType()))
                && (this.getAutoStop() == null ? other.getAutoStop() == null : this.getAutoStop().equals(other.getAutoStop()))
                && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
                && (this.getParam() == null ? other.getParam() == null : this.getParam().equals(other.getParam()))
                && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_op_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getOpType() == null) ? 0 : getOpType().hashCode());
        result = prime * result + ((getAutoStop() == null) ? 0 : getAutoStop().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getParam() == null) ? 0 : getParam().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        return result;
    }
}