package com.zzwl.ias.domain;

import java.util.Date;

public class DeviceStateChangeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_state_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_state_log.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_state_log.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_state_log.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_state_log.id
     *
     * @return the value of dev_state_log.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_state_log.id
     *
     * @param id the value for dev_state_log.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_state_log.dev_id
     *
     * @return the value of dev_state_log.dev_id
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_state_log.dev_id
     *
     * @param devId the value for dev_state_log.dev_id
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_state_log.time
     *
     * @return the value of dev_state_log.time
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_state_log.time
     *
     * @param time the value for dev_state_log.time
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_state_log.state
     *
     * @return the value of dev_state_log.state
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_state_log.state
     *
     * @param state the value for dev_state_log.state
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_state_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DeviceStateChangeRecord other = (DeviceStateChangeRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()))
                && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
                && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_state_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        return result;
    }
}