package com.zzwl.ias.domain;

import java.util.Date;

public class DeviceStatusDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_status.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_status.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_status.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_status.old_state
     *
     * @mbg.generated
     */
    private Integer oldState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_status.new_state
     *
     * @mbg.generated
     */
    private Integer newState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_status.id
     *
     * @return the value of device_status.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_status.id
     *
     * @param id the value for device_status.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_status.dev_id
     *
     * @return the value of device_status.dev_id
     *
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_status.dev_id
     *
     * @param devId the value for device_status.dev_id
     *
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_status.time
     *
     * @return the value of device_status.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_status.time
     *
     * @param time the value for device_status.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_status.old_state
     *
     * @return the value of device_status.old_state
     *
     * @mbg.generated
     */
    public Integer getOldState() {
        return oldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_status.old_state
     *
     * @param oldState the value for device_status.old_state
     *
     * @mbg.generated
     */
    public void setOldState(Integer oldState) {
        this.oldState = oldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_status.new_state
     *
     * @return the value of device_status.new_state
     *
     * @mbg.generated
     */
    public Integer getNewState() {
        return newState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_status.new_state
     *
     * @param newState the value for device_status.new_state
     *
     * @mbg.generated
     */
    public void setNewState(Integer newState) {
        this.newState = newState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DeviceStatusDO other = (DeviceStatusDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getOldState() == null ? other.getOldState() == null : this.getOldState().equals(other.getOldState()))
            && (this.getNewState() == null ? other.getNewState() == null : this.getNewState().equals(other.getNewState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_status
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getOldState() == null) ? 0 : getOldState().hashCode());
        result = prime * result + ((getNewState() == null) ? 0 : getNewState().hashCode());
        return result;
    }
}