package com.zzwl.ias.domain;

public class IasPumpRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ias_pump.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ias_pump.iasystem_id
     *
     * @mbg.generated
     */
    private Integer iasystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ias_pump.pump_id
     *
     * @mbg.generated
     */
    private Long pumpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ias_pump.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ias_pump.id
     *
     * @return the value of ias_pump.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ias_pump.id
     *
     * @param id the value for ias_pump.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ias_pump.iasystem_id
     *
     * @return the value of ias_pump.iasystem_id
     * @mbg.generated
     */
    public Integer getIasystemId() {
        return iasystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ias_pump.iasystem_id
     *
     * @param iasystemId the value for ias_pump.iasystem_id
     * @mbg.generated
     */
    public void setIasystemId(Integer iasystemId) {
        this.iasystemId = iasystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ias_pump.pump_id
     *
     * @return the value of ias_pump.pump_id
     * @mbg.generated
     */
    public Long getPumpId() {
        return pumpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ias_pump.pump_id
     *
     * @param pumpId the value for ias_pump.pump_id
     * @mbg.generated
     */
    public void setPumpId(Long pumpId) {
        this.pumpId = pumpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ias_pump.name
     *
     * @return the value of ias_pump.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ias_pump.name
     *
     * @param name the value for ias_pump.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ias_pump
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IasPumpRecord other = (IasPumpRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getIasystemId() == null ? other.getIasystemId() == null : this.getIasystemId().equals(other.getIasystemId()))
                && (this.getPumpId() == null ? other.getPumpId() == null : this.getPumpId().equals(other.getPumpId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ias_pump
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIasystemId() == null) ? 0 : getIasystemId().hashCode());
        result = prime * result + ((getPumpId() == null) ? 0 : getPumpId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }
}