package com.zzwl.ias.domain;

public class InfoSubjectCatArticleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject_cat_article.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject_cat_article.subjectId
     *
     * @mbg.generated
     */
    private Short subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject_cat_article.subjectCatId
     *
     * @mbg.generated
     */
    private Short subjectCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject_cat_article.articleId
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject_cat_article.id
     *
     * @return the value of info_subject_cat_article.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject_cat_article.id
     *
     * @param id the value for info_subject_cat_article.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject_cat_article.subjectId
     *
     * @return the value of info_subject_cat_article.subjectId
     *
     * @mbg.generated
     */
    public Short getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject_cat_article.subjectId
     *
     * @param subjectId the value for info_subject_cat_article.subjectId
     *
     * @mbg.generated
     */
    public void setSubjectId(Short subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject_cat_article.subjectCatId
     *
     * @return the value of info_subject_cat_article.subjectCatId
     *
     * @mbg.generated
     */
    public Short getSubjectCatId() {
        return subjectCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject_cat_article.subjectCatId
     *
     * @param subjectCatId the value for info_subject_cat_article.subjectCatId
     *
     * @mbg.generated
     */
    public void setSubjectCatId(Short subjectCatId) {
        this.subjectCatId = subjectCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject_cat_article.articleId
     *
     * @return the value of info_subject_cat_article.articleId
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject_cat_article.articleId
     *
     * @param articleId the value for info_subject_cat_article.articleId
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InfoSubjectCatArticleDO other = (InfoSubjectCatArticleDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSubjectId() == null ? other.getSubjectId() == null : this.getSubjectId().equals(other.getSubjectId()))
            && (this.getSubjectCatId() == null ? other.getSubjectCatId() == null : this.getSubjectCatId().equals(other.getSubjectCatId()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject_cat_article
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSubjectId() == null) ? 0 : getSubjectId().hashCode());
        result = prime * result + ((getSubjectCatId() == null) ? 0 : getSubjectCatId().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        return result;
    }
}