package com.zzwl.ias.domain;

import java.util.Date;

public class InfoSubjectDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.originImg
     *
     * @mbg.generated
     */
    private String originImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.watchCount
     *
     * @mbg.generated
     */
    private Short watchCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.commentCount
     *
     * @mbg.generated
     */
    private Short commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.publishTime
     *
     * @mbg.generated
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_subject.origin
     *
     * @mbg.generated
     */
    private String origin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.id
     *
     * @return the value of info_subject.id
     *
     * @mbg.generated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.id
     *
     * @param id the value for info_subject.id
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.title
     *
     * @return the value of info_subject.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.title
     *
     * @param title the value for info_subject.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.img
     *
     * @return the value of info_subject.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.img
     *
     * @param img the value for info_subject.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.originImg
     *
     * @return the value of info_subject.originImg
     *
     * @mbg.generated
     */
    public String getOriginImg() {
        return originImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.originImg
     *
     * @param originImg the value for info_subject.originImg
     *
     * @mbg.generated
     */
    public void setOriginImg(String originImg) {
        this.originImg = originImg == null ? null : originImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.watchCount
     *
     * @return the value of info_subject.watchCount
     *
     * @mbg.generated
     */
    public Short getWatchCount() {
        return watchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.watchCount
     *
     * @param watchCount the value for info_subject.watchCount
     *
     * @mbg.generated
     */
    public void setWatchCount(Short watchCount) {
        this.watchCount = watchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.commentCount
     *
     * @return the value of info_subject.commentCount
     *
     * @mbg.generated
     */
    public Short getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.commentCount
     *
     * @param commentCount the value for info_subject.commentCount
     *
     * @mbg.generated
     */
    public void setCommentCount(Short commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.publishTime
     *
     * @return the value of info_subject.publishTime
     *
     * @mbg.generated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.publishTime
     *
     * @param publishTime the value for info_subject.publishTime
     *
     * @mbg.generated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.summary
     *
     * @return the value of info_subject.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.summary
     *
     * @param summary the value for info_subject.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_subject.origin
     *
     * @return the value of info_subject.origin
     *
     * @mbg.generated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_subject.origin
     *
     * @param origin the value for info_subject.origin
     *
     * @mbg.generated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InfoSubjectDO other = (InfoSubjectDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getImg() == null ? other.getImg() == null : this.getImg().equals(other.getImg()))
            && (this.getOriginImg() == null ? other.getOriginImg() == null : this.getOriginImg().equals(other.getOriginImg()))
            && (this.getWatchCount() == null ? other.getWatchCount() == null : this.getWatchCount().equals(other.getWatchCount()))
            && (this.getCommentCount() == null ? other.getCommentCount() == null : this.getCommentCount().equals(other.getCommentCount()))
            && (this.getPublishTime() == null ? other.getPublishTime() == null : this.getPublishTime().equals(other.getPublishTime()))
            && (this.getSummary() == null ? other.getSummary() == null : this.getSummary().equals(other.getSummary()))
            && (this.getOrigin() == null ? other.getOrigin() == null : this.getOrigin().equals(other.getOrigin()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_subject
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getImg() == null) ? 0 : getImg().hashCode());
        result = prime * result + ((getOriginImg() == null) ? 0 : getOriginImg().hashCode());
        result = prime * result + ((getWatchCount() == null) ? 0 : getWatchCount().hashCode());
        result = prime * result + ((getCommentCount() == null) ? 0 : getCommentCount().hashCode());
        result = prime * result + ((getPublishTime() == null) ? 0 : getPublishTime().hashCode());
        result = prime * result + ((getSummary() == null) ? 0 : getSummary().hashCode());
        result = prime * result + ((getOrigin() == null) ? 0 : getOrigin().hashCode());
        return result;
    }
}