package com.zzwl.ias.domain;

public class IrrigationAreaRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_irr_area.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_irr_area.fm_id
     *
     * @mbg.generated
     */
    private Integer fmId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_irr_area.id
     *
     * @return the value of fm_irr_area.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_irr_area.id
     *
     * @param id the value for fm_irr_area.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_irr_area.fm_id
     *
     * @return the value of fm_irr_area.fm_id
     * @mbg.generated
     */
    public Integer getFmId() {
        return fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_irr_area.fm_id
     *
     * @param fmId the value for fm_irr_area.fm_id
     * @mbg.generated
     */
    public void setFmId(Integer fmId) {
        this.fmId = fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_irr_area
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IrrigationAreaRecordKey other = (IrrigationAreaRecordKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getFmId() == null ? other.getFmId() == null : this.getFmId().equals(other.getFmId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_irr_area
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFmId() == null) ? 0 : getFmId().hashCode());
        return result;
    }
}