package com.zzwl.ias.domain;

import java.util.Date;

public class IrrigationTaskRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.ias_id
     *
     * @mbg.generated
     */
    private Integer iasId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.farmland_id
     *
     * @mbg.generated
     */
    private Integer farmlandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.irri_area_id
     *
     * @mbg.generated
     */
    private Integer irriAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.delete_user
     *
     * @mbg.generated
     */
    private Integer deleteUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.exp_duration
     *
     * @mbg.generated
     */
    private Integer expDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_task.irri_duration
     *
     * @mbg.generated
     */
    private Integer irriDuration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.id
     *
     * @return the value of irrigation_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.id
     *
     * @param id the value for irrigation_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.ias_id
     *
     * @return the value of irrigation_task.ias_id
     *
     * @mbg.generated
     */
    public Integer getIasId() {
        return iasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.ias_id
     *
     * @param iasId the value for irrigation_task.ias_id
     *
     * @mbg.generated
     */
    public void setIasId(Integer iasId) {
        this.iasId = iasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.farmland_id
     *
     * @return the value of irrigation_task.farmland_id
     *
     * @mbg.generated
     */
    public Integer getFarmlandId() {
        return farmlandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.farmland_id
     *
     * @param farmlandId the value for irrigation_task.farmland_id
     *
     * @mbg.generated
     */
    public void setFarmlandId(Integer farmlandId) {
        this.farmlandId = farmlandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.irri_area_id
     *
     * @return the value of irrigation_task.irri_area_id
     *
     * @mbg.generated
     */
    public Integer getIrriAreaId() {
        return irriAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.irri_area_id
     *
     * @param irriAreaId the value for irrigation_task.irri_area_id
     *
     * @mbg.generated
     */
    public void setIrriAreaId(Integer irriAreaId) {
        this.irriAreaId = irriAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.create_time
     *
     * @return the value of irrigation_task.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.create_time
     *
     * @param createTime the value for irrigation_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.start_time
     *
     * @return the value of irrigation_task.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.start_time
     *
     * @param startTime the value for irrigation_task.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.finish_time
     *
     * @return the value of irrigation_task.finish_time
     *
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.finish_time
     *
     * @param finishTime the value for irrigation_task.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.create_user
     *
     * @return the value of irrigation_task.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.create_user
     *
     * @param createUser the value for irrigation_task.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.delete_user
     *
     * @return the value of irrigation_task.delete_user
     *
     * @mbg.generated
     */
    public Integer getDeleteUser() {
        return deleteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.delete_user
     *
     * @param deleteUser the value for irrigation_task.delete_user
     *
     * @mbg.generated
     */
    public void setDeleteUser(Integer deleteUser) {
        this.deleteUser = deleteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.status
     *
     * @return the value of irrigation_task.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.status
     *
     * @param status the value for irrigation_task.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.result
     *
     * @return the value of irrigation_task.result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.result
     *
     * @param result the value for irrigation_task.result
     *
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.exp_duration
     *
     * @return the value of irrigation_task.exp_duration
     *
     * @mbg.generated
     */
    public Integer getExpDuration() {
        return expDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.exp_duration
     *
     * @param expDuration the value for irrigation_task.exp_duration
     *
     * @mbg.generated
     */
    public void setExpDuration(Integer expDuration) {
        this.expDuration = expDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_task.irri_duration
     *
     * @return the value of irrigation_task.irri_duration
     *
     * @mbg.generated
     */
    public Integer getIrriDuration() {
        return irriDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_task.irri_duration
     *
     * @param irriDuration the value for irrigation_task.irri_duration
     *
     * @mbg.generated
     */
    public void setIrriDuration(Integer irriDuration) {
        this.irriDuration = irriDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table irrigation_task
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IrrigationTaskRecord other = (IrrigationTaskRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIasId() == null ? other.getIasId() == null : this.getIasId().equals(other.getIasId()))
            && (this.getFarmlandId() == null ? other.getFarmlandId() == null : this.getFarmlandId().equals(other.getFarmlandId()))
            && (this.getIrriAreaId() == null ? other.getIrriAreaId() == null : this.getIrriAreaId().equals(other.getIrriAreaId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getFinishTime() == null ? other.getFinishTime() == null : this.getFinishTime().equals(other.getFinishTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getDeleteUser() == null ? other.getDeleteUser() == null : this.getDeleteUser().equals(other.getDeleteUser()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getExpDuration() == null ? other.getExpDuration() == null : this.getExpDuration().equals(other.getExpDuration()))
            && (this.getIrriDuration() == null ? other.getIrriDuration() == null : this.getIrriDuration().equals(other.getIrriDuration()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table irrigation_task
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIasId() == null) ? 0 : getIasId().hashCode());
        result = prime * result + ((getFarmlandId() == null) ? 0 : getFarmlandId().hashCode());
        result = prime * result + ((getIrriAreaId() == null) ? 0 : getIrriAreaId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getFinishTime() == null) ? 0 : getFinishTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getDeleteUser() == null) ? 0 : getDeleteUser().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getExpDuration() == null) ? 0 : getExpDuration().hashCode());
        result = prime * result + ((getIrriDuration() == null) ? 0 : getIrriDuration().hashCode());
        return result;
    }
}