package com.zzwl.ias.domain;

import java.util.Date;

public class IrrigationAreaRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.ias_id
     *
     * @mbg.generated
     */
    private Integer iasId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.fm_id
     *
     * @mbg.generated
     */
    private Integer fmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column irrigation_area.sort_order
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.id
     *
     * @return the value of irrigation_area.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.id
     *
     * @param id the value for irrigation_area.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.ias_id
     *
     * @return the value of irrigation_area.ias_id
     * @mbg.generated
     */
    public Integer getIasId() {
        return iasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.ias_id
     *
     * @param iasId the value for irrigation_area.ias_id
     * @mbg.generated
     */
    public void setIasId(Integer iasId) {
        this.iasId = iasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.fm_id
     *
     * @return the value of irrigation_area.fm_id
     * @mbg.generated
     */
    public Integer getFmId() {
        return fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.fm_id
     *
     * @param fmId the value for irrigation_area.fm_id
     * @mbg.generated
     */
    public void setFmId(Integer fmId) {
        this.fmId = fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.name
     *
     * @return the value of irrigation_area.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.name
     *
     * @param name the value for irrigation_area.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.create_time
     *
     * @return the value of irrigation_area.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.create_time
     *
     * @param createTime the value for irrigation_area.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.is_delete
     *
     * @return the value of irrigation_area.is_delete
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.is_delete
     *
     * @param isDelete the value for irrigation_area.is_delete
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.delete_time
     *
     * @return the value of irrigation_area.delete_time
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.delete_time
     *
     * @param deleteTime the value for irrigation_area.delete_time
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column irrigation_area.sort_order
     *
     * @return the value of irrigation_area.sort_order
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column irrigation_area.sort_order
     *
     * @param sortOrder the value for irrigation_area.sort_order
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table irrigation_area
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IrrigationAreaRecord other = (IrrigationAreaRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getIasId() == null ? other.getIasId() == null : this.getIasId().equals(other.getIasId()))
                && (this.getFmId() == null ? other.getFmId() == null : this.getFmId().equals(other.getFmId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
                && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()))
                && (this.getSortOrder() == null ? other.getSortOrder() == null : this.getSortOrder().equals(other.getSortOrder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table irrigation_area
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIasId() == null) ? 0 : getIasId().hashCode());
        result = prime * result + ((getFmId() == null) ? 0 : getFmId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        result = prime * result + ((getSortOrder() == null) ? 0 : getSortOrder().hashCode());
        return result;
    }
}