package com.zzwl.ias.domain;

import java.util.Date;

public class LatestIrrRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.irr_area_id
     *
     * @mbg.generated
     */
    private Integer irrAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.iasystem_id
     *
     * @mbg.generated
     */
    private Integer iasystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.fm_id
     *
     * @mbg.generated
     */
    private Integer fmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_irri_log.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.irr_area_id
     *
     * @return the value of latest_irri_log.irr_area_id
     * @mbg.generated
     */
    public Integer getIrrAreaId() {
        return irrAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.irr_area_id
     *
     * @param irrAreaId the value for latest_irri_log.irr_area_id
     * @mbg.generated
     */
    public void setIrrAreaId(Integer irrAreaId) {
        this.irrAreaId = irrAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.iasystem_id
     *
     * @return the value of latest_irri_log.iasystem_id
     * @mbg.generated
     */
    public Integer getIasystemId() {
        return iasystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.iasystem_id
     *
     * @param iasystemId the value for latest_irri_log.iasystem_id
     * @mbg.generated
     */
    public void setIasystemId(Integer iasystemId) {
        this.iasystemId = iasystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.fm_id
     *
     * @return the value of latest_irri_log.fm_id
     * @mbg.generated
     */
    public Integer getFmId() {
        return fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.fm_id
     *
     * @param fmId the value for latest_irri_log.fm_id
     * @mbg.generated
     */
    public void setFmId(Integer fmId) {
        this.fmId = fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.duration
     *
     * @return the value of latest_irri_log.duration
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.duration
     *
     * @param duration the value for latest_irri_log.duration
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.add_time
     *
     * @return the value of latest_irri_log.add_time
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.add_time
     *
     * @param addTime the value for latest_irri_log.add_time
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.start_time
     *
     * @return the value of latest_irri_log.start_time
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.start_time
     *
     * @param startTime the value for latest_irri_log.start_time
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.finish_time
     *
     * @return the value of latest_irri_log.finish_time
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.finish_time
     *
     * @param finishTime the value for latest_irri_log.finish_time
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_irri_log.result
     *
     * @return the value of latest_irri_log.result
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_irri_log.result
     *
     * @param result the value for latest_irri_log.result
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table latest_irri_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LatestIrrRecord other = (LatestIrrRecord) that;
        return (this.getIrrAreaId() == null ? other.getIrrAreaId() == null : this.getIrrAreaId().equals(other.getIrrAreaId()))
                && (this.getIasystemId() == null ? other.getIasystemId() == null : this.getIasystemId().equals(other.getIasystemId()))
                && (this.getFmId() == null ? other.getFmId() == null : this.getFmId().equals(other.getFmId()))
                && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
                && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
                && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
                && (this.getFinishTime() == null ? other.getFinishTime() == null : this.getFinishTime().equals(other.getFinishTime()))
                && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table latest_irri_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIrrAreaId() == null) ? 0 : getIrrAreaId().hashCode());
        result = prime * result + ((getIasystemId() == null) ? 0 : getIasystemId().hashCode());
        result = prime * result + ((getFmId() == null) ? 0 : getFmId().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getFinishTime() == null) ? 0 : getFinishTime().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        return result;
    }
}