package com.zzwl.ias.domain;

import java.util.Date;

public class MessageAlarmRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.sersor_id
     *
     * @mbg.generated
     */
    private Long sersorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.is_read
     *
     * @mbg.generated
     */
    private Byte isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.alarm_threshold_id
     *
     * @mbg.generated
     */
    private Integer alarmThresholdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.alarm_type
     *
     * @mbg.generated
     */
    private Byte alarmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.threshold
     *
     * @mbg.generated
     */
    private Integer threshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.occur_time
     *
     * @mbg.generated
     */
    private Date occurTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_alarm.end_reason
     *
     * @mbg.generated
     */
    private Integer endReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.id
     *
     * @return the value of message_alarm.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.id
     *
     * @param id the value for message_alarm.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.sersor_id
     *
     * @return the value of message_alarm.sersor_id
     * @mbg.generated
     */
    public Long getSersorId() {
        return sersorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.sersor_id
     *
     * @param sersorId the value for message_alarm.sersor_id
     * @mbg.generated
     */
    public void setSersorId(Long sersorId) {
        this.sersorId = sersorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.title
     *
     * @return the value of message_alarm.title
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.title
     *
     * @param title the value for message_alarm.title
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.content
     *
     * @return the value of message_alarm.content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.content
     *
     * @param content the value for message_alarm.content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.is_read
     *
     * @return the value of message_alarm.is_read
     * @mbg.generated
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.is_read
     *
     * @param isRead the value for message_alarm.is_read
     * @mbg.generated
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.alarm_threshold_id
     *
     * @return the value of message_alarm.alarm_threshold_id
     * @mbg.generated
     */
    public Integer getAlarmThresholdId() {
        return alarmThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.alarm_threshold_id
     *
     * @param alarmThresholdId the value for message_alarm.alarm_threshold_id
     * @mbg.generated
     */
    public void setAlarmThresholdId(Integer alarmThresholdId) {
        this.alarmThresholdId = alarmThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.data_type
     *
     * @return the value of message_alarm.data_type
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.data_type
     *
     * @param dataType the value for message_alarm.data_type
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.alarm_type
     *
     * @return the value of message_alarm.alarm_type
     * @mbg.generated
     */
    public Byte getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.alarm_type
     *
     * @param alarmType the value for message_alarm.alarm_type
     * @mbg.generated
     */
    public void setAlarmType(Byte alarmType) {
        this.alarmType = alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.level
     *
     * @return the value of message_alarm.level
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.level
     *
     * @param level the value for message_alarm.level
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.status
     *
     * @return the value of message_alarm.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.status
     *
     * @param status the value for message_alarm.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.threshold
     *
     * @return the value of message_alarm.threshold
     * @mbg.generated
     */
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.threshold
     *
     * @param threshold the value for message_alarm.threshold
     * @mbg.generated
     */
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.occur_time
     *
     * @return the value of message_alarm.occur_time
     * @mbg.generated
     */
    public Date getOccurTime() {
        return occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.occur_time
     *
     * @param occurTime the value for message_alarm.occur_time
     * @mbg.generated
     */
    public void setOccurTime(Date occurTime) {
        this.occurTime = occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.end_time
     *
     * @return the value of message_alarm.end_time
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.end_time
     *
     * @param endTime the value for message_alarm.end_time
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_alarm.end_reason
     *
     * @return the value of message_alarm.end_reason
     * @mbg.generated
     */
    public Integer getEndReason() {
        return endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_alarm.end_reason
     *
     * @param endReason the value for message_alarm.end_reason
     * @mbg.generated
     */
    public void setEndReason(Integer endReason) {
        this.endReason = endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_alarm
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MessageAlarmRecord other = (MessageAlarmRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getSersorId() == null ? other.getSersorId() == null : this.getSersorId().equals(other.getSersorId()))
                && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
                && (this.getIsRead() == null ? other.getIsRead() == null : this.getIsRead().equals(other.getIsRead()))
                && (this.getAlarmThresholdId() == null ? other.getAlarmThresholdId() == null : this.getAlarmThresholdId().equals(other.getAlarmThresholdId()))
                && (this.getDataType() == null ? other.getDataType() == null : this.getDataType().equals(other.getDataType()))
                && (this.getAlarmType() == null ? other.getAlarmType() == null : this.getAlarmType().equals(other.getAlarmType()))
                && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getThreshold() == null ? other.getThreshold() == null : this.getThreshold().equals(other.getThreshold()))
                && (this.getOccurTime() == null ? other.getOccurTime() == null : this.getOccurTime().equals(other.getOccurTime()))
                && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
                && (this.getEndReason() == null ? other.getEndReason() == null : this.getEndReason().equals(other.getEndReason()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_alarm
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSersorId() == null) ? 0 : getSersorId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getIsRead() == null) ? 0 : getIsRead().hashCode());
        result = prime * result + ((getAlarmThresholdId() == null) ? 0 : getAlarmThresholdId().hashCode());
        result = prime * result + ((getDataType() == null) ? 0 : getDataType().hashCode());
        result = prime * result + ((getAlarmType() == null) ? 0 : getAlarmType().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getThreshold() == null) ? 0 : getThreshold().hashCode());
        result = prime * result + ((getOccurTime() == null) ? 0 : getOccurTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getEndReason() == null) ? 0 : getEndReason().hashCode());
        return result;
    }
}