package com.zzwl.ias.domain;

public class NormalDeviceRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_device_normal.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_device_normal.fm_id
     *
     * @mbg.generated
     */
    private Integer fmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_device_normal.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_device_normal.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_device_normal.id
     *
     * @return the value of fm_device_normal.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_device_normal.id
     *
     * @param id the value for fm_device_normal.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_device_normal.fm_id
     *
     * @return the value of fm_device_normal.fm_id
     * @mbg.generated
     */
    public Integer getFmId() {
        return fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_device_normal.fm_id
     *
     * @param fmId the value for fm_device_normal.fm_id
     * @mbg.generated
     */
    public void setFmId(Integer fmId) {
        this.fmId = fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_device_normal.name
     *
     * @return the value of fm_device_normal.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_device_normal.name
     *
     * @param name the value for fm_device_normal.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_device_normal.dev_id
     *
     * @return the value of fm_device_normal.dev_id
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_device_normal.dev_id
     *
     * @param devId the value for fm_device_normal.dev_id
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_device_normal
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NormalDeviceRecord other = (NormalDeviceRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getFmId() == null ? other.getFmId() == null : this.getFmId().equals(other.getFmId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_device_normal
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFmId() == null) ? 0 : getFmId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        return result;
    }
}