package com.zzwl.ias.domain;

import java.util.Date;

public class WarningDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.sub_type
     *
     * @mbg.generated
     */
    private Integer subType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.cleared
     *
     * @mbg.generated
     */
    private Boolean cleared;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.produce_time
     *
     * @mbg.generated
     */
    private Date produceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.clear_time
     *
     * @mbg.generated
     */
    private Date clearTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.clear_reason
     *
     * @mbg.generated
     */
    private Integer clearReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.addr_type
     *
     * @mbg.generated
     */
    private Integer addrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.addr_ias
     *
     * @mbg.generated
     */
    private Integer addrIas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.addr_irri_fer
     *
     * @mbg.generated
     */
    private Integer addrIrriFer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.addr_farmland
     *
     * @mbg.generated
     */
    private Integer addrFarmland;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.addr_area
     *
     * @mbg.generated
     */
    private Integer addrArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.addr_parent_dev
     *
     * @mbg.generated
     */
    private Integer addrParentDev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.addr_dev
     *
     * @mbg.generated
     */
    private Integer addrDev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning.extension
     *
     * @mbg.generated
     */
    private Object extension;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.id
     *
     * @return the value of warning.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.id
     *
     * @param id the value for warning.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.type
     *
     * @return the value of warning.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.type
     *
     * @param type the value for warning.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.sub_type
     *
     * @return the value of warning.sub_type
     *
     * @mbg.generated
     */
    public Integer getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.sub_type
     *
     * @param subType the value for warning.sub_type
     *
     * @mbg.generated
     */
    public void setSubType(Integer subType) {
        this.subType = subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.level
     *
     * @return the value of warning.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.level
     *
     * @param level the value for warning.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.cleared
     *
     * @return the value of warning.cleared
     *
     * @mbg.generated
     */
    public Boolean getCleared() {
        return cleared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.cleared
     *
     * @param cleared the value for warning.cleared
     *
     * @mbg.generated
     */
    public void setCleared(Boolean cleared) {
        this.cleared = cleared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.produce_time
     *
     * @return the value of warning.produce_time
     *
     * @mbg.generated
     */
    public Date getProduceTime() {
        return produceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.produce_time
     *
     * @param produceTime the value for warning.produce_time
     *
     * @mbg.generated
     */
    public void setProduceTime(Date produceTime) {
        this.produceTime = produceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.clear_time
     *
     * @return the value of warning.clear_time
     *
     * @mbg.generated
     */
    public Date getClearTime() {
        return clearTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.clear_time
     *
     * @param clearTime the value for warning.clear_time
     *
     * @mbg.generated
     */
    public void setClearTime(Date clearTime) {
        this.clearTime = clearTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.clear_reason
     *
     * @return the value of warning.clear_reason
     *
     * @mbg.generated
     */
    public Integer getClearReason() {
        return clearReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.clear_reason
     *
     * @param clearReason the value for warning.clear_reason
     *
     * @mbg.generated
     */
    public void setClearReason(Integer clearReason) {
        this.clearReason = clearReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.addr_type
     *
     * @return the value of warning.addr_type
     *
     * @mbg.generated
     */
    public Integer getAddrType() {
        return addrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.addr_type
     *
     * @param addrType the value for warning.addr_type
     *
     * @mbg.generated
     */
    public void setAddrType(Integer addrType) {
        this.addrType = addrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.addr_ias
     *
     * @return the value of warning.addr_ias
     *
     * @mbg.generated
     */
    public Integer getAddrIas() {
        return addrIas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.addr_ias
     *
     * @param addrIas the value for warning.addr_ias
     *
     * @mbg.generated
     */
    public void setAddrIas(Integer addrIas) {
        this.addrIas = addrIas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.addr_irri_fer
     *
     * @return the value of warning.addr_irri_fer
     *
     * @mbg.generated
     */
    public Integer getAddrIrriFer() {
        return addrIrriFer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.addr_irri_fer
     *
     * @param addrIrriFer the value for warning.addr_irri_fer
     *
     * @mbg.generated
     */
    public void setAddrIrriFer(Integer addrIrriFer) {
        this.addrIrriFer = addrIrriFer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.addr_farmland
     *
     * @return the value of warning.addr_farmland
     *
     * @mbg.generated
     */
    public Integer getAddrFarmland() {
        return addrFarmland;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.addr_farmland
     *
     * @param addrFarmland the value for warning.addr_farmland
     *
     * @mbg.generated
     */
    public void setAddrFarmland(Integer addrFarmland) {
        this.addrFarmland = addrFarmland;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.addr_area
     *
     * @return the value of warning.addr_area
     *
     * @mbg.generated
     */
    public Integer getAddrArea() {
        return addrArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.addr_area
     *
     * @param addrArea the value for warning.addr_area
     *
     * @mbg.generated
     */
    public void setAddrArea(Integer addrArea) {
        this.addrArea = addrArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.addr_parent_dev
     *
     * @return the value of warning.addr_parent_dev
     *
     * @mbg.generated
     */
    public Integer getAddrParentDev() {
        return addrParentDev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.addr_parent_dev
     *
     * @param addrParentDev the value for warning.addr_parent_dev
     *
     * @mbg.generated
     */
    public void setAddrParentDev(Integer addrParentDev) {
        this.addrParentDev = addrParentDev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.addr_dev
     *
     * @return the value of warning.addr_dev
     *
     * @mbg.generated
     */
    public Integer getAddrDev() {
        return addrDev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.addr_dev
     *
     * @param addrDev the value for warning.addr_dev
     *
     * @mbg.generated
     */
    public void setAddrDev(Integer addrDev) {
        this.addrDev = addrDev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning.extension
     *
     * @return the value of warning.extension
     *
     * @mbg.generated
     */
    public Object getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning.extension
     *
     * @param extension the value for warning.extension
     *
     * @mbg.generated
     */
    public void setExtension(Object extension) {
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WarningDO other = (WarningDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSubType() == null ? other.getSubType() == null : this.getSubType().equals(other.getSubType()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getCleared() == null ? other.getCleared() == null : this.getCleared().equals(other.getCleared()))
            && (this.getProduceTime() == null ? other.getProduceTime() == null : this.getProduceTime().equals(other.getProduceTime()))
            && (this.getClearTime() == null ? other.getClearTime() == null : this.getClearTime().equals(other.getClearTime()))
            && (this.getClearReason() == null ? other.getClearReason() == null : this.getClearReason().equals(other.getClearReason()))
            && (this.getAddrType() == null ? other.getAddrType() == null : this.getAddrType().equals(other.getAddrType()))
            && (this.getAddrIas() == null ? other.getAddrIas() == null : this.getAddrIas().equals(other.getAddrIas()))
            && (this.getAddrIrriFer() == null ? other.getAddrIrriFer() == null : this.getAddrIrriFer().equals(other.getAddrIrriFer()))
            && (this.getAddrFarmland() == null ? other.getAddrFarmland() == null : this.getAddrFarmland().equals(other.getAddrFarmland()))
            && (this.getAddrArea() == null ? other.getAddrArea() == null : this.getAddrArea().equals(other.getAddrArea()))
            && (this.getAddrParentDev() == null ? other.getAddrParentDev() == null : this.getAddrParentDev().equals(other.getAddrParentDev()))
            && (this.getAddrDev() == null ? other.getAddrDev() == null : this.getAddrDev().equals(other.getAddrDev()))
            && (this.getExtension() == null ? other.getExtension() == null : this.getExtension().equals(other.getExtension()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSubType() == null) ? 0 : getSubType().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getCleared() == null) ? 0 : getCleared().hashCode());
        result = prime * result + ((getProduceTime() == null) ? 0 : getProduceTime().hashCode());
        result = prime * result + ((getClearTime() == null) ? 0 : getClearTime().hashCode());
        result = prime * result + ((getClearReason() == null) ? 0 : getClearReason().hashCode());
        result = prime * result + ((getAddrType() == null) ? 0 : getAddrType().hashCode());
        result = prime * result + ((getAddrIas() == null) ? 0 : getAddrIas().hashCode());
        result = prime * result + ((getAddrIrriFer() == null) ? 0 : getAddrIrriFer().hashCode());
        result = prime * result + ((getAddrFarmland() == null) ? 0 : getAddrFarmland().hashCode());
        result = prime * result + ((getAddrArea() == null) ? 0 : getAddrArea().hashCode());
        result = prime * result + ((getAddrParentDev() == null) ? 0 : getAddrParentDev().hashCode());
        result = prime * result + ((getAddrDev() == null) ? 0 : getAddrDev().hashCode());
        result = prime * result + ((getExtension() == null) ? 0 : getExtension().hashCode());
        return result;
    }
}