package com.zzwl.ias.domain;

public class WstationIasRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wstation_ias.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wstation_ias.weather_station_id
     *
     * @mbg.generated
     */
    private Integer weatherStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wstation_ias.ias_id
     *
     * @mbg.generated
     */
    private Integer iasId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wstation_ias.id
     *
     * @return the value of wstation_ias.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wstation_ias.id
     *
     * @param id the value for wstation_ias.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wstation_ias.weather_station_id
     *
     * @return the value of wstation_ias.weather_station_id
     * @mbg.generated
     */
    public Integer getWeatherStationId() {
        return weatherStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wstation_ias.weather_station_id
     *
     * @param weatherStationId the value for wstation_ias.weather_station_id
     * @mbg.generated
     */
    public void setWeatherStationId(Integer weatherStationId) {
        this.weatherStationId = weatherStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wstation_ias.ias_id
     *
     * @return the value of wstation_ias.ias_id
     * @mbg.generated
     */
    public Integer getIasId() {
        return iasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wstation_ias.ias_id
     *
     * @param iasId the value for wstation_ias.ias_id
     * @mbg.generated
     */
    public void setIasId(Integer iasId) {
        this.iasId = iasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WstationIasRecord other = (WstationIasRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getWeatherStationId() == null ? other.getWeatherStationId() == null : this.getWeatherStationId().equals(other.getWeatherStationId()))
                && (this.getIasId() == null ? other.getIasId() == null : this.getIasId().equals(other.getIasId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wstation_ias
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWeatherStationId() == null) ? 0 : getWeatherStationId().hashCode());
        result = prime * result + ((getIasId() == null) ? 0 : getIasId().hashCode());
        return result;
    }
}